// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/duc-cnzj/kt-demo/internal/biz"
	"github.com/duc-cnzj/kt-demo/internal/conf"
	"github.com/duc-cnzj/kt-demo/internal/data"
	"github.com/duc-cnzj/kt-demo/internal/server"
	"github.com/duc-cnzj/kt-demo/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	demoRepo := data.NewDemoRepo(logger, dataData)
	demoBase := biz.NewDemoBase(demoRepo, logger)
	demoService := service.NewDemoService(demoBase, logger)
	grpcServer := server.NewGRPCServer(confServer, demoService, logger)
	httpServer := server.NewHTTPServer(confServer, demoService, logger)
	registrar := data.NewReg()
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
